/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package net.skyebook.viewportcolorchooser;

import com.jme3.gde.core.scene.SceneApplication;
import java.awt.Color;
import javax.naming.NameAlreadyBoundException;
import org.openide.util.NbPreferences;

final class ColorPanel extends javax.swing.JPanel {

    private final ColorOptionsPanelController controller;

    ColorPanel(ColorOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewportColorChooser = new javax.swing.JColorChooser();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewportColorChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewportColorChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        viewportColorChooser.setColor(
                new Color(NbPreferences.forModule(ColorPanel.class).
                getInt("viewportColor", Color.black.getRGB())));
    }

    void store() {
        // Apply the color
        SceneApplication.getApplication().getViewPort().
                        setBackgroundColor(
                ColorConverter.fromAWT(viewportColorChooser.getColor()));
        
        // Save it to the preferences
        NbPreferences.forModule(ColorPanel.class).
                putInt("viewportColor", viewportColorChooser.getColor().getRGB());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser viewportColorChooser;
    // End of variables declaration//GEN-END:variables
}
